# Generated by Django 4.2.23 on 2025-07-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_discount_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
