# Generated by Django 4.2.23 on 2025-07-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
    ]
