# Generated by Django 4.2.23 on 2025-07-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_low_stock_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
    ]
