# Generated by Django 4.2.23 on 2025-07-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
    ]
