# Generated by Django 4.2.23 on 2025-07-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_discount_product_stock'),
        ('cart', '0002_cartitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
