# Generated by Django 4.2.23 on 2025-07-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='category',
        ),
    ]
